#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 3.6
  #- 2.7

services: sqlite3

env:
  - DJANGO=1.11.7

before_install:
  - export DJANGO_SETTINGS_MODULE=modelstest.settings
  - export PYTHONPATH=$HOME/builds/mublan11/SABUAZ
  - export PIP_USE_MIRRORS=true

install:
  #- pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install djangorestframework coreapi markdown django-filter django-crispy-forms django-guardian
  - pip install coverage==4.4.2
  #- pip install psycopg2 --quiet

before_script:
  #- psql -c "CREATE DATABASE mydb;" -U postgres

script:
  #- python manage.py syncdb --noinput
  - python manage.py test apps/solicitante/tests
  - python manage.py test apps/casaestudiantil/tests
  - python manage.py test apps/comedor/tests 
  - python manage.py test apps/supervisor/tests
  - python manage.py test apps/serviciosexternos/tests

notifications:
  email: #false
    - jerad.salinas94@gmail.com