#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 3.6
  #- 2.7

services: sqlite3

env:
  - DJANGO=1.11.7

before_install:
  - export DJANGO_SETTINGS_MODULE=modelstest.settings
  - export PYTHONPATH=$HOME/builds/mublan11/SABUAZ
  - export PIP_USE_MIRRORS=true
addons: # get google-chrome-stable
  chrome: stable
  
install:
  #- pip install -r requirements.txt
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - pip install django==$DJANGO --quiet
  - pip install djangorestframework coreapi markdown django-filter django-crispy-forms django-guardian
  - pip install coverage==4.4.2
  - pip install django-cors-headers
  - pip install lettuce
  - pip install selenium
  - pip install nose==1.3.0
  - pip install beautifulsoup4==4.1.3
  #- pip install psycopg2 --quiet

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  #- psql -c "CREATE DATABASE mydb;" -U postgres

script:
  #- python manage.py syncdb --noinput
  - python manage.py test apps/solicitante/tests
  - python manage.py test apps/casaestudiantil/tests
  - python manage.py test apps/comedor/tests 
  - python manage.py test apps/supervisor/tests
  - python manage.py test apps/serviciosexternos/tests
  - make run-tests

notifications:
  email: 
    false