# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comedor', '0001_initial'),
        ('casaestudiantil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='apellido_paterno')),
                ('apellido_materno', models.CharField(max_length=50, null=True, verbose_name='apellido_materno')),
                ('casas_estudiantil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casaestudiantil.CasaEstudiantil')),
                ('comedor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.Comedor')),
            ],
        ),
    ]
