# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAcademicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=8, unique=True, verbose_name='matricula')),
                ('promedio', models.FloatField(verbose_name='promedio')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_beca', models.CharField(choices=[('ALIMENTACION', 'ALIMENTACION'), ('HOSPEDAJE', 'HOSPEDAJE'), ('ALIMENTACION Y HOSPEDAJE', 'ALIMENTACION Y HOSPEDAJE')], max_length=25)),
                ('tipo_solicitud', models.CharField(choices=[('RENOVACION', 'RENOVACION'), ('NUEVO INGRESO', 'NUEVO INGRESO')], max_length=25)),
                ('estudio_socioeconomico', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('comprobante_ingresos', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('ine_padres', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('comprobante_inscripcion', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('boleta_calificaciones', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('carta_compromiso_padres', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('comprobante_solicitud_linea', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=6, null=True, verbose_name='numero')),
                ('calle', models.CharField(max_length=50, verbose_name='calle')),
                ('colonia', models.CharField(max_length=50, verbose_name='colonia')),
                ('codigo_postal', models.CharField(max_length=5, verbose_name='codigo_postal')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='ZACATECAS', max_length=50, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=50, verbose_name='municipio')),
                ('estado_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaLicenciatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='apellido_paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='apellido_materno')),
                ('sexo', models.CharField(choices=[('HOMBRE', 'HOMBRE'), ('MUJER', 'MUJER')], max_length=10, verbose_name='sexo')),
                ('status', models.CharField(blank=True, choices=[('ACEPTADA', 'ACEPTADA'), ('PENDIENTE', 'PENDIENTE'), ('RECHAZADA', 'RECHAZADA')], max_length=10, null=True, verbose_name='status')),
                ('datos_academicos_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitante.DatosAcademicos')),
                ('documentos_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.Documentos')),
                ('domicilio_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.Domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10, verbose_name='telefono')),
                ('tipo', models.CharField(choices=[('FIJO', 'FIJO'), ('CELULAR', 'CELULAR')], default='FIJO', max_length=10, verbose_name='tipo')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='nombre')),
            ],
        ),
        migrations.AddField(
            model_name='solicitante',
            name='telefono_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.Telefono'),
        ),
        migrations.AddField(
            model_name='programalicenciatura',
            name='unidad_academica_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.UnidadAcademica'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.Estado'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.Municipio'),
        ),
        migrations.AddField(
            model_name='datosacademicos',
            name='programa_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.ProgramaLicenciatura'),
        ),
        migrations.AddField(
            model_name='datosacademicos',
            name='unidad_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.UnidadAcademica'),
        ),
    ]
